### PR TITLE
Pull request for chores

### PR DESCRIPTION
**Pull request by sduthil**
## add zuul + tox

### CODE REVIEW

**Review by fblackburn1 — APPROVED** [review]
Oh interesting
- Not 100% sure about the "right place" for this kind of tool. This tool should help internal and external developer to develop on wazo, maybe not standardize our repo (which is a task for internal Wazo development, not external). But it's only my though and probably more convenient to leave it here.
- The archive list will be a pain to maintain (not as much than a list of all repos). I would prefer to fetch them from github directly. I guess we can add a flag later and cache result and on the first run print a error message to execute the command with the flag :man_shrugging: 
- Same thinking about how we check chores (local vs github). If your repo is not up-to-date, then you will have false positive.

Overall, it's a nice first step. I don't have objection to merge.
Thank you

Edit: adding this repo to zuul, waiting for reconfiguration and I'll trigger recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by sduthil** [comment]
>     * Not 100% sure about the "right place" for this kind of tool. This tool should help internal and external developer to develop on wazo, maybe not standardize our repo (which is a task for internal Wazo development, not external). But it's only my though and probably more convenient to leave it here.

IMHO external developers may also want a list of "low-hanging fruits", most chores should be relatively easy to handle, provided a good example.

>     * The archive list will be a pain to maintain (not as much than a list of all repos). I would prefer to fetch them from github directly. I guess we can add a flag later and cache result and on the first run print a error message to execute the command with the flag man_shrugging

I totally agree and had the same thinking. As you say, it's a first step.

>     * Same thinking about how we check chores (local vs github). If your repo is not up-to-date, then you will have false positive.

I always forget that one, thanks for the comment :)

**Pull request merged**
