### PR TITLE
Use Python3 for agid, confgend and provd.

### PR DESCRIPTION
**Pull request by sopelj**

### CODE REVIEW

**Review by fblackburn1 — CHANGES_REQUESTED** [review]
Until we have not removed python2 for `*-client` repo, we should keep them

**Comment by sopelj** [comment]
> Until we have not removed python2 for `*-client` repo, we should keep them

Just for `*-client` libraries? We can I suppose, it's only default values though. You can still set `python2: true` for any one of them if you need to.

**Comment by fblackburn1** [comment]
> > Until we have not removed python2 for `*-client` repo, we should keep them
> 
> Just for `*-client` libraries? We can I suppose, it's only default values though. You can still set `python2: true` for any one of them if you need to.

No for all libraries supporting python2 and python3 until we remove the python2 support, we must keep them to avoid mounting partial code and create headache to developers (wazo or not) using these dependencies.
In practice, they should not be use. But they should be removed only after removing python2 from these repository to avoid inconsistency

**Comment by sopelj** [comment]
> > > Until we have not removed python2 for `*-client` repo, we should keep them
> > 
> > 
> > Just for `*-client` libraries? We can I suppose, it's only default values though. You can still set `python2: true` for any one of them if you need to.
> 
> No for all libraries supporting python2 and python3 until we remove the python2 support, we must keep them to avoid mounting partial code and create headache to developers (wazo or not) using these dependencies. In practice, they should not be use. But they should be removed only after removing python2 from these repository to avoid inconsistency

Ok, I suppose. Is there any reason we still need the old Python 2 versions or can we just stop building them? I can happily remove the python2 build if you'd like.

**Comment by fblackburn1** [comment]
> Ok, I suppose. Is there any reason we still need the old Python 2 versions or can we just stop building them? I can happily remove the python2 build if you'd like.

Nop removing them will be the next step :smile: 
https://wazo-dev.atlassian.net/browse/WAZO-2840

**Comment by sopelj** [comment]
> > Ok, I suppose. Is there any reason we still need the old Python 2 versions or can we just stop building them? I can happily remove the python2 build if you'd like.
> 
> Nop removing them will be the next step smile https://wazo-dev.atlassian.net/browse/WAZO-2840

Looking forward to that. In the meantime I restored the `python2` options to the example config for clients as per your request. So it is now just a fix for provd, confgend and agid who were still at python2 and should be python3.

**Review by fblackburn1 — APPROVED** [review]

**Pull request merged**
